<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class CustomizationUploadController extends Controller
{
    /**
     * Upload custom logo for garment customization overlay
     */
    public function uploadLogo(Request $request)
    {
        $request->validate([
            'logo' => 'required|image|mimes:jpeg,png,jpg,gif,svg,webp|max:10240',
        ]);

        if ($request->hasFile('logo')) {
            $file = $request->file('logo');
            $filename = 'logo_' . time() . '_' . Str::random(8) . '.' . $file->getClientOriginalExtension();
            
            $destinationPath = public_path('uploads/logos');
            if (!file_exists($destinationPath)) {
                mkdir($destinationPath, 0777, true);
            }
            
            $file->move($destinationPath, $filename);
            $relativeUrl = 'uploads/logos/' . $filename;
            $fullUrl = asset($relativeUrl);

            return response()->json([
                'success' => true,
                'url' => $fullUrl,
                'relative_url' => $relativeUrl,
                'filename' => $filename,
                'message' => 'Logo uploaded successfully'
            ]);
        }

        return response()->json([
            'success' => false,
            'message' => 'No logo file provided'
        ], 400);
    }

    /**
     * Save base64 / blob preview screenshot generated by html2canvas
     */
    public function uploadPreview(Request $request)
    {
        $images = $request->input('images');
        $urls = [];

        if (is_array($images) && count($images) > 0) {
            foreach ($images as $viewKey => $base64Data) {
                if ($base64Data && preg_match('/^data:image\/(\w+);base64,/', $base64Data, $type)) {
                    $raw = base64_decode(substr($base64Data, strpos($base64Data, ',') + 1));
                    if ($raw !== false) {
                        $ext = strtolower($type[1]);
                        if (!in_array($ext, ['jpg', 'jpeg', 'gif', 'png', 'webp'])) $ext = 'png';
                        
                        $filename = 'preview_' . $viewKey . '_' . time() . '_' . Str::random(6) . '.' . $ext;
                        $destinationPath = public_path('uploads/customization/screenshots');
                        if (!file_exists($destinationPath)) mkdir($destinationPath, 0777, true);
                        file_put_contents($destinationPath . '/' . $filename, $raw);
                        $urls[$viewKey] = asset('uploads/customization/screenshots/' . $filename);
                    }
                }
            }
        }

        // Single image fallback
        $imgData = $request->input('image');
        $singleUrl = null;
        if ($imgData && preg_match('/^data:image\/(\w+);base64,/', $imgData, $type)) {
            $raw = base64_decode(substr($imgData, strpos($imgData, ',') + 1));
            if ($raw !== false) {
                $ext = strtolower($type[1]);
                if (!in_array($ext, ['jpg', 'jpeg', 'gif', 'png', 'webp'])) $ext = 'png';
                $filename = 'preview_main_' . time() . '_' . Str::random(6) . '.' . $ext;
                $destinationPath = public_path('uploads/customization/screenshots');
                if (!file_exists($destinationPath)) mkdir($destinationPath, 0777, true);
                file_put_contents($destinationPath . '/' . $filename, $raw);
                $singleUrl = asset('uploads/customization/screenshots/' . $filename);
                if (empty($urls['front'])) $urls['front'] = $singleUrl;
            }
        }

        return response()->json([
            'success' => true,
            'url' => $singleUrl ?? ($urls['front'] ?? (reset($urls) ?: null)),
            'urls' => $urls,
            'message' => 'Preview screenshots saved successfully'
        ]);
    }
}
